name : hello
on:
  push:
   branches:
    - main
jobs:
 firstheloworkjob:
    runs-on: ubuntu latest
    steps:
      -name: checkout code
      uses: actions/checkout@v3
      name : print message
      run : echo "Hello word"
