name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  firsthelloworldjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello world"
